import type { Finding, Measurement } from "@/lib/types";
import { UncertaintyBar } from "./UncertaintyBar";
import { VerdictBadge } from "./VerdictBadge";
function thresholdFromRequired(required: string) { const number = required.match(/\d+(?:\.\d+)?/); return number ? Number(number[0]) : null; }
// The frozen contract carries a single uncertainty field, expanded_uncertainty_mm, for every
// metric — including contrast_ratio, which is dimensionless. Printing "mm" beside a ratio puts
// a wrong unit on a screen the panel reads, so the unit comes from the metric rather than the
// field name. Renaming the contract field would need all three lanes in the room.
function unitFor(metric: string) { return metric.endsWith("_mm") ? "mm" : null; }
export function MeasurementCard({ measurement, finding }: { measurement: Measurement; finding?: Finding }) { const threshold = finding ? thresholdFromRequired(finding.required) : null; const unit = unitFor(measurement.metric); return <article className="panel p-5"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Calibrated measurement</p><h3 className="mt-1 font-semibold capitalize text-slate-950">{measurement.field.replace("_", " ")} · {measurement.metric.replaceAll("_", " ")}</h3></div>{finding && <VerdictBadge verdict={finding.verdict} />}</div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><div><p className="text-xs font-medium text-slate-500">Measured value</p><p className="mt-1 text-2xl font-semibold text-slate-950">{measurement.value.toFixed(2)}{unit && <> <span className="text-sm">{unit}</span></>}</p></div><div><p className="text-xs font-medium text-slate-500">Expanded uncertainty</p><p className="mt-1 text-2xl font-semibold text-slate-950">± {measurement.expanded_uncertainty_mm.toFixed(2)}{unit && <> <span className="text-sm">{unit}</span></>}</p><p className="text-xs text-slate-500">k = {measurement.k}</p></div>{finding && <div><p className="text-xs font-medium text-slate-500">Legal requirement</p><p className="mt-1 text-lg font-semibold text-slate-950">{finding.required}</p></div>}</div>{finding && threshold !== null && <UncertaintyBar value={measurement.value} uncertainty={measurement.expanded_uncertainty_mm} threshold={threshold} verdict={finding.verdict} />}</article>; }
