/**
 * The runnable check for stage 5.
 *
 * check-contract.mjs proves the fixtures have the right SHAPE. This proves the rule engine
 * reaches the right VERDICT over them — including the two cases that matter more than any
 * happy path: a measurement whose interval straddles the threshold must come back
 * INDETERMINATE, and a thing that was never measured must never come back a VIOLATION.
 *
 *     npm run check:evaluate
 */

import { readFileSync } from "node:fs";
import assert from "node:assert/strict";
import { evaluate, rollup } from "../lib/evaluate.ts";
import type { EvaluableScan, RulePack } from "../lib/evaluate.ts";
import type { LabelField } from "../lib/types.ts";

const pack = JSON.parse(
  readFileSync("packs/lmpc-2026-07-01.json", "utf8"),
) as RulePack;

const read = (p: string) => JSON.parse(readFileSync(p, "utf8")) as EvaluableScan;

const byRef = (findings: { rule_ref: string; verdict: string }[], ref: string) =>
  findings.filter((f) => f.rule_ref === ref).map((f) => f.verdict);

// ---------------------------------------------------------------------------
// The two frozen fixtures
// ---------------------------------------------------------------------------

const sample = read("fixtures/scan.sample.json");
const sampleOut = evaluate(sample, pack);

assert.deepEqual(byRef(sampleOut.findings, "7(3)").sort(), ["COMPLIANT", "VIOLATION"],
  "sample: MRP height is 0.82 ± 0.10 against a 1 mm floor — a violation; the width ratio clears");
assert.deepEqual(byRef(sampleOut.findings, "7(2)"), ["INDETERMINATE"],
  "sample: net quantity 1.03 ± 0.14 straddles the 1 mm threshold and must stay open");
assert.deepEqual(byRef(sampleOut.findings, "6(2)"), ["COMPLIANT"],
  "sample: consumer care details are present");
assert.equal(sampleOut.overall, "VIOLATION", "sample: worst-wins rollup");

// Rule 8(1). This fixture used to record a VIOLATION its own geometry could not produce: the
// "20% EXTRA" flash was drawn at x 402–520, y 318–352 against a numeral at x 286–330,
// y 394–418 — 2.97 mm clear horizontally and 1.73 mm vertically, against requirements of 2.06
// and 1.03 — while the stored finding asserted "1.8 mm from the declaration", a number nothing
// computed. The flash has since been moved to where such a flash actually sits on a pack, just
// below and beside the declaration, so the violation this fixture exists to demonstrate is now
// one the engine derives rather than one the file asserts. Every finding in fixtures/ is now
// generated by evaluate(); if you edit a polygon, regenerate rather than editing a verdict.
assert.deepEqual(byRef(sampleOut.findings, "8(1)"), ["VIOLATION"],
  "sample: the promotional flash intrudes on the declaration's required clear space");

// The stored findings must BE the engine's output, not a hand-written approximation of it.
// They drifted before: the fixtures carried four findings while the pack had grown to seven,
// so every screen reading fixtures/ under-reported the law against the same scan evaluated live.
{
  const stored = JSON.parse(readFileSync("fixtures/scan.sample.json", "utf8")) as {
    findings: unknown[]; overall: string;
  };
  assert.deepEqual(stored.findings, JSON.parse(JSON.stringify(sampleOut.findings)),
    "fixtures/scan.sample.json findings must be regenerated from evaluate(), not edited by hand");
  assert.equal(stored.overall, sampleOut.overall, "sample: stored overall must match the rollup");
}

const compliant = read("fixtures/scan.compliant.json");
const compliantOut = evaluate(compliant, pack);
assert.ok(
  compliantOut.findings.every((f) => f.verdict === "COMPLIANT"),
  "compliant fixture: every rule should pass",
);
assert.equal(compliantOut.overall, "COMPLIANT");

{
  const stored = JSON.parse(readFileSync("fixtures/scan.compliant.json", "utf8")) as {
    findings: unknown[]; overall: string;
  };
  assert.deepEqual(stored.findings, JSON.parse(JSON.stringify(compliantOut.findings)),
    "fixtures/scan.compliant.json findings must be regenerated from evaluate(), not edited by hand");
  assert.equal(stored.overall, compliantOut.overall);
}

// ---------------------------------------------------------------------------
// Guard bands — the behaviour the project exists to get right
// ---------------------------------------------------------------------------

const base = structuredClone(compliant);
const heightRule = pack.rules.filter((r) => r.id === "r7-3-letter-height");
const onlyHeight: RulePack = { ...pack, rules: heightRule };
const mrpHeight = (s: EvaluableScan) =>
  s.measurements.find((m) => m.field === "mrp" && m.metric === "numeral_height_mm")!;

{
  const s = structuredClone(base);
  const m = mrpHeight(s);
  m.value = 1.02;
  m.expanded_uncertainty_mm = 0.15; // 0.87 … 1.17 — straddles 1 mm
  assert.equal(evaluate(s, onlyHeight).findings[0].verdict, "INDETERMINATE",
    "an interval straddling the threshold is never a verdict");
}

{
  const s = structuredClone(base);
  const m = mrpHeight(s);
  m.value = 0.5;
  m.expanded_uncertainty_mm = 0.05; // 0.45 … 0.55 — wholly below
  assert.equal(evaluate(s, onlyHeight).findings[0].verdict, "VIOLATION",
    "an interval wholly below the threshold is a violation");
}

{
  const s = structuredClone(base);
  s.measurements = s.measurements.filter(
    (m) => !(m.field === "mrp" && m.metric === "numeral_height_mm"),
  );
  assert.equal(evaluate(s, onlyHeight).findings[0].verdict, "INDETERMINATE",
    "a thing that was never measured is not an offence");
}

{
  // Low extractor confidence holds a violation open: the model chose which string was the
  // MRP, and a violation resting on an uncertain choice is an accusation we cannot support.
  const s = structuredClone(base);
  const m = mrpHeight(s);
  m.value = 0.5;
  m.expanded_uncertainty_mm = 0.05;
  const mrp = s.fields.find((f) => f.key === "mrp")!;
  mrp.confidence = 0.4;
  assert.equal(evaluate(s, onlyHeight).findings[0].verdict, "INDETERMINATE",
    "a violation on a low-confidence field is held open");

  mrp.corrected_by_officer = true;
  assert.equal(evaluate(s, onlyHeight).findings[0].verdict, "VIOLATION",
    "an officer confirming the field restores the violation");
}

{
  // Clear space, with print that genuinely intrudes: same row as the numeral, 10 px away
  // at 0.0412 mm/px — 0.41 mm against the 2 × 1.48 mm required.
  const s = structuredClone(compliant);
  s.other_print = [{ poly: [[340, 394], [420, 394], [420, 418], [340, 418]], note: "flash" }];
  const clearRule: RulePack = {
    ...pack,
    rules: pack.rules.filter((r) => r.id === "r8-1-clear-space"),
  };
  assert.equal(evaluate(s, clearRule).findings[0].verdict, "VIOLATION",
    "print beside the declaration inside the required space is a violation");
}

{
  // A rule the pipeline structurally cannot judge is reported, not folded into the verdict.
  // If this regresses, every scan goes INDETERMINATE forever the moment Rule 9(1)(b) enters
  // a pack — which would read on stage as caution and actually be a bug.
  // Built from one known rule rather than the whole pack, so the count below stays true as
  // Advik adds rules the pipeline cannot yet judge.
  const withUnassessable: RulePack = {
    ...pack,
    rules: [
      ...pack.rules.filter((r) => r.id === "r7-3-letter-height"),
      {
        id: "x-contrast",
        rule_ref: "9(1)(b)",
        rule_text:
          "numerals of the retail sale price and net quantity declaration shall be printed, painted or inscribed on the package in a colour that contrasts conspicuously with the background of the label;",
        applies_to: "mrp",
        predicate: "contrast_min",
        message: "The numerals do not contrast conspicuously with the background.",
      },
    ],
  };
  const out = evaluate(structuredClone(compliant), withUnassessable);
  assert.equal(out.not_assessed.length, 1, "the unjudgeable rule is reported");
  assert.equal(out.not_assessed[0].rule_ref, "9(1)(b)");
  assert.ok(out.not_assessed[0].reason.length > 20, "and it says why");
  assert.ok(
    out.findings.every((f) => f.rule_ref !== "9(1)(b)"),
    "it produces no finding, because no finding was reached",
  );
  assert.equal(out.overall, "COMPLIANT",
    "a check that never ran must not hold the whole scan open");
}

// ---------------------------------------------------------------------------
// Absence of evidence, for the textual predicates.
//
// A declaration the extractor returned NO entry for was never assessed, so it cannot be an
// offence. A declaration it DID locate and that came back empty is evidence of absence, and
// that one is. Both textual predicates must draw the line in the same place.
// ---------------------------------------------------------------------------

for (const predicate of ["present", "matches"] as const) {
  const rule = pack.rules.find((r) => r.predicate === predicate);
  assert.ok(rule, `the pack must carry a ${predicate} rule for this check to mean anything`);
  const only: RulePack = { ...pack, rules: [rule] };
  const key = rule.applies_to;

  assert.ok(
    compliant.fields.some((f) => f.key === key),
    `fixture must carry a ${key} field for the ${predicate} check`,
  );

  const blank = structuredClone(compliant);
  blank.fields = blank.fields.map((f) => (f.key === key ? { ...f, text: "" } : f));
  assert.equal(
    evaluate(blank, only).findings[0].verdict, "VIOLATION",
    `${predicate}: a located but empty ${key} is evidence of absence, so it is an offence`,
  );

  const missing = structuredClone(compliant);
  missing.fields = missing.fields.filter((f) => f.key !== key);
  assert.equal(
    evaluate(missing, only).findings[0].verdict, "INDETERMINATE",
    `${predicate}: ${key} was never extracted, so it must be held open, never accused`,
  );
}

// ---------------------------------------------------------------------------
// A finding's message must never contradict the verdict it sits under.
//
// A rule pack's `message` is written for the offence. It used to be attached to anything
// that was not COMPLIANT, so a measurement whose interval merely straddled the limit came
// back INDETERMINATE captioned "Net quantity numeral is below the minimum height required
// for this pack size" — an accusation printed under a verdict that says we cannot tell,
// on a document an officer signs.
// ---------------------------------------------------------------------------

{
  const offenceWordings = new Set(pack.rules.map((r) => r.message));
  for (const [label, out] of [["sample", sampleOut], ["compliant", compliantOut]] as const) {
    for (const finding of out.findings) {
      if (finding.verdict === "COMPLIANT") {
        assert.equal(finding.message, null,
          `${label}: a compliant ${finding.rule_ref} must carry no message`);
      }
      if (finding.verdict === "INDETERMINATE") {
        assert.ok(finding.message, `${label}: ${finding.rule_ref} must say why it is open`);
        assert.ok(!offenceWordings.has(finding.message ?? ""),
          `${label}: ${finding.rule_ref} is INDETERMINATE but is captioned with the pack's ` +
          `offence wording: "${finding.message}"`);
      }
    }
  }

  // The same applies to a violation held open for low extractor confidence: the message was
  // chosen from the pre-guard verdict, so it kept the accusation the guard had just withdrawn.
  const s = structuredClone(compliant);
  const m = mrpHeight(s);
  m.value = 0.5;
  m.expanded_uncertainty_mm = 0.05;
  const mrp = s.fields.find((f) => f.key === "mrp");
  assert.ok(mrp, "the compliant fixture must carry an mrp field");
  mrp.confidence = 0.4;
  const held = evaluate(s, onlyHeight).findings[0];
  assert.equal(held.verdict, "INDETERMINATE");
  assert.ok(!offenceWordings.has(held.message ?? ""),
    `a violation held open for low confidence must not keep the accusation: "${held.message}"`);
}

// ---------------------------------------------------------------------------
// Rule 6(1)(e), against how declarations are actually printed.
//
// The pattern is three lookaheads over the declaration text. Without the `s` flag a `.*`
// lookahead stops at a newline, so "MRP ₹45" above "(incl. of all taxes)" — the ordinary
// two-line layout on Indian packaging — matched nothing and a compliant pack was reported
// as a VIOLATION. The dotted "M.R.P." was missing from the alternation for the same reason.
// These are the cases that put a false accusation in front of a manufacturer.
// ---------------------------------------------------------------------------

{
  const rule = pack.rules.find((r) => r.id === "r6-1-e-mrp-form");
  assert.ok(rule, "the pack must still carry the 6(1)(e) rule");
  const only: RulePack = { ...pack, rules: [rule] };
  const verdictForText = (text: string) => {
    const s = structuredClone(compliant);
    s.fields = s.fields.map((f) => (f.key === "mrp" ? { ...f, text } : f));
    return evaluate(s, only).findings[0].verdict;
  };

  for (const text of [
    "MRP ₹45.00 (incl. of all taxes)",
    "MRP ₹45.00\n(incl. of all taxes)",
    "M.R.P. ₹45.00 (incl. of all taxes)",
    "M.R.P. Rs 120\n(Incl. of all taxes)",
    "Maximum Retail Price\n₹45.00 inclusive of all taxes",
  ]) {
    assert.equal(verdictForText(text), "COMPLIANT",
      `6(1)(e) must accept a compliant declaration printed as ${JSON.stringify(text)}`);
  }

  // The rule still has to bite: a price that never says it is the maximum, inclusive of
  // taxes, is a real offence and must not be swept up by a laxer pattern.
  assert.equal(verdictForText("Rs 45.00 only"), "VIOLATION",
    "6(1)(e): a bare price is still an offence");
  assert.equal(verdictForText("MRP ₹45.00"), "VIOLATION",
    "6(1)(e): an MRP that omits the tax statement is still an offence");
}

// ---------------------------------------------------------------------------
// Rule 6(1)(c) — an unparsed declaration is an open question, not an offence.
// ---------------------------------------------------------------------------

{
  const rule = pack.rules.find((r) => r.id === "r6-1-c-net-qty-unit");
  assert.ok(rule, "the pack must still carry the 6(1)(c) rule");
  const only: RulePack = { ...pack, rules: [rule] };
  const verdictForValue = (value: LabelField["value"]) => {
    const s = structuredClone(compliant);
    s.fields = s.fields.map((f) => (f.key === "net_qty" ? { ...f, value } : f));
    return evaluate(s, only).findings[0].verdict;
  };

  assert.equal(verdictForValue({ n: 100, unit: "g" }), "COMPLIANT", "grams are a standard unit");
  assert.equal(verdictForValue({ n: 100, unit: "furlong" }), "VIOLATION",
    "a unit outside the standard set is an offence");
  // Reading the raw string as though it were the unit accused a perfectly legal "500 g" of
  // being declared in a non-standard unit. Extraction failing to structure a declaration
  // says nothing about whether the pack complies.
  assert.equal(verdictForValue("500 g"), "INDETERMINATE",
    "a declaration extraction could not structure must be held open, never accused");
}

// ---------------------------------------------------------------------------
// Rule 7(2) — Table I band selection, at the boundaries where it changes.
// ---------------------------------------------------------------------------

{
  const only: RulePack = { ...pack, rules: pack.rules.filter((r) => r.id === "r7-2-table-i") };
  const requiredFor = (n: number, unit: string) => {
    const s = structuredClone(compliant);
    s.fields = s.fields.map((f) => (f.key === "net_qty" ? { ...f, value: { n, unit } } : f));
    return evaluate(s, only).findings[0].required;
  };

  assert.match(requiredFor(200, "g"), /≥ 1\.00 mm/, "200 g is the top of the first band");
  assert.match(requiredFor(201, "g"), /≥ 2\.00 mm/, "201 g crosses into the second band");
  assert.match(requiredFor(500, "g"), /≥ 2\.00 mm/, "500 g is the top of the second band");
  assert.match(requiredFor(501, "g"), /≥ 4\.00 mm/, "above 500 g takes the largest height");
  assert.match(requiredFor(1, "kg"), /≥ 4\.00 mm/, "a kilogram is 1000 g, above every band");
  assert.match(requiredFor(250, "ml"), /≥ 2\.00 mm/, "millilitres use the same table as grams");
}

// ---------------------------------------------------------------------------
// Rule 7(3) ratio — a degenerate measurement must not reach the officer as NaN.
// ---------------------------------------------------------------------------

{
  const s = structuredClone(compliant);
  const width = s.measurements.find(
    (m) => m.field === "mrp" && m.metric === "numeral_width_mm",
  );
  assert.ok(width, "the compliant fixture must carry an MRP width for this check");
  width.value = 0;
  const only: RulePack = { ...pack, rules: pack.rules.filter((r) => r.id === "r7-3-width-ratio") };
  const finding = evaluate(s, only).findings[0];
  assert.equal(finding.verdict, "INDETERMINATE", "a zero width is not a ratio");
  // 0 × Infinity is NaN, and the string below is printed on a report an officer signs.
  assert.ok(!finding.measured.includes("NaN"),
    `a report must never print NaN, got "${finding.measured}"`);
}

// ---------------------------------------------------------------------------
// Rollup
// ---------------------------------------------------------------------------

assert.equal(rollup([{ verdict: "COMPLIANT" }, { verdict: "INDETERMINATE" }]), "INDETERMINATE");
assert.equal(rollup([{ verdict: "INDETERMINATE" }, { verdict: "VIOLATION" }]), "VIOLATION");
assert.equal(rollup([{ verdict: "COMPLIANT" }]), "COMPLIANT");

console.log(
  `ok — rule engine agrees with both fixtures over ${pack.rules.length} rules, guard bands hold`,
);
